### ISSUE TITLE
What is the bug you are demonstrating in this repo?

### ISSUE THREAD

**Issue by bbrandt** [clement128/ServiceBusDemo#1]
I am looking to use Azure.Messaging.ServiceBus and am a but concerned at the existence of this repo.  Thanks for any help.  :-)

**Comment by clement128** [comment]
oh @bbrandt thinks for pointing out this. actually it's typo, it should be `Bus`

**Comment by bbrandt** [comment]
Ah, got it!  Then thank you so much for the excellent example.  😄
